config/routes.rb
Rails.application.routes.draw do
  root to: 'dishes#show' #show details of a dish on the root

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/restaurant'

  resources :users

  resources :restaurants do
    resources :dishes
    resources :images
    resources :restaurant_ratings do 
      resources :restaurant_rating_comments
    end
  end
resources :restaurant_ratings do 
      resources :restaurant_rating_comments
    end
  
  resources :dishes do
    resources :posts do
      resources :images
      resources :post_comments
    end
    resources :images
    resources :dish_ratings do
      resources :dish_rating_comments
    end
  end

  resources :posts do
    resources :images
    resources :post_comments
  end

  resources :restaurant_ratings do
    resources :restaurant_rating_comments
  end

  resources :post_comments

  resources :dish_rating_comments

  resources :dish_ratings

  resources :images

end

app/models/restaurant_rating.rb
class RestaurantRating < ActiveRecord::Base
  validates :rate_value, :presence => true
  validates :user_id, :presence => true
  validates :restaurant_id, :presence => true
  
  #relationships
  belongs_to :restaurant
  belongs_to :user
  has_many :restaurant_rating_comments, dependent: :destroy
  
end

app/controllers/restaurant_ratings_controller.rb
class RestaurantRatingsController < ApplicationController
  before_action :set_restaurant_rating, only: [:show, :edit, :update, :destroy, :new]
  
  before_filter :set_restaurant

  # GET /restaurant_ratings
  # GET /restaurant_ratings.json
  def index
    @restaurant_ratings = @restaurant.restaurant_ratings
  end

  # GET /restaurant_ratings/1
  # GET /restaurant_ratings/1.json
  def show
  end

  # GET /restaurant_ratings/new
  def new
   
    @restaurant_rating = @restaurant.restaurant_ratings.new
  end

  # GET /restaurant_ratings/1/edit
  def edit
  end

  # POST /restaurant_ratings
  # POST /restaurant_ratings.json
  def create

    @restaurant_rating = @restaurant.restaurant_ratings.new(restaurant_rating_params)

    respond_to do |format|
      if @restaurant_rating.save
        format.html { redirect_to @restaurant_rating, notice: 'Restaurant rating was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant_rating }
      else
        format.html { render :new }
        format.json { render json: @restaurant_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurant_ratings/1
  # PATCH/PUT /restaurant_ratings/1.json

  def update

    respond_to do |format|
      if @restaurant_rating.update(params[:restaurant_rating])
        format.html { redirect_to @restaurant_rating, notice: 'Restaurant rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant_rating }
      else
        format.html { render :edit }
        format.json { render json: @restaurant_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant_ratings/1
  # DELETE /restaurant_ratings/1.json
  def destroy
    
    @restaurant_rating.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_ratings_url, notice: 'Restaurant rating was successfully destroyed.' }
      format.json { head :no_content }
      format.js  #can respond to javascript
    end
  end
  
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant_rating
      @restaurant_rating = @restaurants.restaurant_ratings.find(params[:id])
    end
  
  private 
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_rating_params
      params.require(:restaurant_rating).permit(:rate_value, :user_id, :restaurant_id, :content, :restaurant_rating)
    end
end

app/helpers/restaurant_ratings_helper.rb
module RestaurantRatingsHelper
end

app/views/restaurant_ratings/_form.html.erb
<%= form_for(@restaurant_rating) do |f| %>
  <% if @restaurant_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant_rating.errors.count, "error") %> prohibited this restaurant_rating from being saved:</h2>

      <ul>
      <% @restaurant_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :rate_value %><br>
    <%= f.text_field :rate_value %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurant_ratings/_index.html.erb
<%= form_for(@restaurant_rating) do |f| %>
  <% if @restaurant_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant_rating.errors.count, "error") %> prohibited this restaurant_rating from being saved:</h2>

      <ul>
      <% @restaurant_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :rate_value %><br>
    <%= f.text_field :rate_value %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurant_ratings/destroy.js.erb
$('#<%= dom_id(@restaurant_raiting) %>').fadeOut();

app/views/restaurant_ratings/edit.html.erb
<h1>Editing restaurant_rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_rating %> |
<%= link_to 'Back', restaurant_ratings_path %>

app/views/restaurant_ratings/index.html.erb
<div class="" style="text-align: left;">
<h1>Listing restaurant_ratings</h1>

<div class="clear_both" style="text-align: left; border: 1px solid black;">
    <% @restaurant_ratings.each do |restaurant_rating| %>
  <%= div_for restaurant_rating, style: "background-color: #FFDBDB;" do %> 
  <table style="width: 100%; border: 1px solid black">
      <tr>
        <td><%= restaurant_rating.user_id %></td>
        <td><%= restaurant_rating.rate_value %></td>        
        <td><%= restaurant_rating.restaurant_id %></td>
    </tr>
    <tr>
      <td colspan="2"><%= restaurant_rating.content %></td>
      <td>
          <div class="actions">       
          <span><%= link_to 'Show', restaurant_rating %></span>
            <span><%= link_to 'Edit', edit_restaurant_restaurant_rating_path(@restaurant, restaurant_rating) %></span>
            <span><%= link_to 'Destroy', [@restaurant, restaurant_rating], method: :delete, data: { confirm: 'Are you sure?' } %></span>
         </div>
      </td>
    </tr>
    <tr>
       <td colspan="3" style="text-align:right;">
          <span class="" ><%= link_to "Add comment",new_restaurant_rating_comment_path %></span>
        </td>
      </tr>
  </table>
    <% end %>
  <% end %>
 </div>

<br/>
  <%= link_to 'New Restaurant rating', new_restaurant_restaurant_rating_path %>
<br/>
  <br/>
</div>

app/views/restaurant_ratings/new.html.erb
<h1>New restaurant_rating</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_ratings_path %>

app/views/restaurant_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate value:</strong>
  <%= @restaurant_rating.rate_value %>
</p>

<p>
  <strong>User:</strong>
  <%= @restaurant_rating.user_id %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @restaurant_rating.restaurant_id %>
</p>

<%= link_to 'Edit', edit_restaurant_restaurant_rating_path(@restaurant, @restaurant_rating) %> |
<%= link_to 'Back', restaurant_ratings_path %>