config/routes.rb
Rails.application.routes.draw do
  root to: 'dishes#show' #show details of a dish on the root

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/restaurant'

  resources :users

  resources :restaurants do
    resources :dishes
    resources :images
    resources :restaurant_ratings do 
      resources :restaurant_rating_comments
    end
  end
resources :restaurant_ratings do 
      resources :restaurant_rating_comments
    end
  
  resources :dishes do
    resources :posts do
      resources :images
      resources :post_comments
    end
    resources :images
    resources :dish_ratings do
      resources :dish_rating_comments
    end
  end

  resources :posts do
    resources :images
    resources :post_comments
  end

  resources :restaurant_ratings do
    resources :restaurant_rating_comments
  end

  resources :post_comments

  resources :dish_rating_comments

  resources :dish_ratings

  resources :images

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :category, :presence => true
  validates :restaurant_id, :presence => true
  #validates :menu_id, :presence => true
  
  #relationships
  belongs_to :restaurant
  #belongs_to :menu
  has_many :posts, dependent: :destroy
  has_many :dish_ratings, dependent: :destroy
  has_many :images, as: :imageable
  
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    # additional code for different response types
    respond_to do |format|
      format.html   # show.html.erb
      format.json {render json: @dish}
    end
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
      format.js  #can respond to javascript
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      #@dish = Dish.find(params[:id])
      if params[:id].nil?
        @dish = Dish.first
      else
         @dish = Dish.find(params[:id])
      end
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :description, :category, :restaurant_id)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>
      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/destroy.js.erb
$('#<%= dom_id(@dish) %>').fadeOut();
//alert("I am an alert box!");

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<div style="text-align: left; padding: 1em;">
<h1 class="">Listing dishes</h1>

<div class="clear_both" style="text-align: left; border: 1px solid black;">
  <% @dishes.each do |dish| %>
    <%= div_for dish do %> 
       <table style="width: 100%;">
          <tr>
            <td class="" style="margin-right: 1em; width: 20%;"> 
              <% if dish.images.count > 0 %>
                <% dish.images.each do |image| %>
                  <% i = image.name %> <% l = image.location_path%>
                  <% path =  l.to_s() + i.to_s() %>
              <%= link_to (image_tag path, height: "", width: "250", alt: dish.name, title: dish.name), dish %>
                <%end%>
              <%end%>
            </td>
            <td class="dish_name" style="width: 25%;"><%= link_to dish.name, dish %></td>
            <td class="dish_category " style="width: 10%;"><%= dish.category %></td>
          <td class="dish_description " style="width: 35%;"><%= dish.description %></td>
          
        <td>
          <div class="actions">
          <span><%= link_to 'View', dish %></span>
          <span><%= link_to 'Edit', edit_dish_path(dish) %></span>
          <!--<span><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' },  remote: true %></span> -->
          </div>
        </td>
      </tr>
    </table>
                        

    <% end %>
  <% end %>
</div>
<br/>

<%= link_to 'New Dish', new_dish_path %>
</div>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<div style="width 100%; border: 1px solid black; text-align: left; margin: 1em; padding: 1em;">
  <h1> Showing dish details</h1>
  <p id="notice"><%= notice %></p>
  <div style="border: 3px solid green;">
    <div id="left_column" style="width: 50%; float: left; border: 1px solid red; margin: 0;">
        <div class="dish_name">
          <%= @dish.name %>
          <span class="right" style="font-size: 0.75em;">Restaurant: <%= link_to @dish.restaurant.name, @dish.restaurant %></span>
        </div>
        <div class="" style="margin-right: 1em; width: 100%;"> 
          <% if @dish.images.count > 0 %>
                <% @dish.images.each do |image| %>
                <% i = image.name %> <% l = image.location_path%>
                <% path =  l.to_s() + i.to_s() %>
                <%= image_tag path, height: "", width: "100%", alt: @dish.name, title: @dish.name %>
              <% end %>
          <%end%>
        </div>
        <%= link_to 'Edit', edit_dish_path(@dish) %> |
  <%= link_to 'Back', dishes_path %>
    </div>
    <div id="right_column" style="width: 45%; border: 1px solid blue; float: left; margin: 0;">
        <div> <strong>Category:</strong> <%= @dish.category %> </div>
        <div class="right"> <strong>Rating:</strong> 5 stars </div>
        <div class="dish_name">Description:</div>
        <div class="dish_description clear_right"><%= @dish.description %></div>  
    </div>
    <div id="right_column" style="width: 25%; border: 1px solid green; float: right; margin: 0;">
    <div class="restaurant_name">Ratings</div>
      <% if @dish.dish_ratings.count > 0 %>
          <% @dish.dish_ratings.each do |dish_ratings| %>
            <%= div_for dish_ratings, style: "background-color: #FFDBDB;" do %> 
                <p class=""><%= dish_ratings.content%></p>
                <p class=""><%= dish_ratings.rate_value%></p>
                <p class="" style="text-align:right;"><%= link_to "Add comment",new_post_comment_path %></p>
                <%end%>
          <%end%>
    <%else%>
      <p>No ratings ...</p>
      <p class="" style="text-align:right;"><%= link_to "Add rating",new_dish_rating_path %></p>
    <%end%>
      
      <p class="right">Add rating</p>
    </div>
    
    
    
 </div>
  <div class="post_list clear_both" style="width 100%; border: 1px solid red; text-align: left; margin: 1em; padding: 1em;">
    List of post
    </div>


    <div id="right_column" style="width: 20%; border: 1px solid green; float: right; margin: 0;">
      <div class="restaurant_name"></div>

        <p>Add rating</p>
      </div>



    <div class="clear_both"></div>




  <div class="" style="border: 1px solid red; text-align: left;">
  </div> <!-- add image -->

    <!-- add new post div-->  
                  <div class="clear_both right" id="new_post" style="">
                        <form action="">
                              Content:<br>
                              <textarea name="message" rows="10" cols="30">
                              </textarea>
                              <br/>
                              Picture:<input type="text" name="pic"><input class="" type="submit" value="browse">
                              <br/><br/>

                              <input class="" type="submit" value="Save">
                              <input class="" type="submit" value="Cancel">
                        </form>
                      </div>








</div>