config/routes.rb
Rails.application.routes.draw do
  root to: 'dishes#show' #show details of a dish on the root

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/restaurant'

  resources :users

  resources :restaurants do
    resources :dishes
    resources :images
    resources :restaurant_ratings do 
      resources :restaurant_rating_comments
    end
  end
resources :restaurant_ratings do 
      resources :restaurant_rating_comments
    end
  
  resources :dishes do
    resources :posts do
      resources :images
      resources :post_comments
    end
    resources :images
    resources :dish_ratings do
      resources :dish_rating_comments
    end
  end

  resources :posts do
    resources :images
    resources :post_comments
  end

  resources :restaurant_ratings do
    resources :restaurant_rating_comments
  end

  resources :post_comments

  resources :dish_rating_comments

  resources :dish_ratings

  resources :images

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :address, :presence => true
  validates :location, :presence => true
  validates :gps_lat, :presence => true
  validates :gps_lon, :presence => true
  validates :category, :presence => true
  
  

  
  #relationships
  #has_many :menus, dependent: :destroy
  has_many :dishes, dependent: :destroy
  has_many :restaurant_ratings, dependent: :destroy
  has_many :images, as: :imageable
  accepts_nested_attributes_for :images
  
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  #actions
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
      format.js  #can respond to javascript
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address, :location, :gps_lat, :gps_lon, :category, images_attributes: [:name, :description, :location_path, :imageable_id, :imageable_type])
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :gps_lat %><br>
    <%= f.text_field :gps_lat %>
  </div>
  <div class="field">
    <%= f.label :gps_lon %><br>
    <%= f.text_field :gps_lon %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/destroy.js.erb
$('#<%= dom_id(@restaurant) %>').fadeOut();

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div style="text-align: left; padding: 1em;">
<h1>Listing restaurants</h1>

<div class="clear_both" style="text-align: left; border: 1px solid black;">
    <% @restaurants.each do |restaurant| %>
  <%= div_for restaurant, style: "background-color: #FFDBDB;" do %> 
  <!-- <% i = restaurant.images.first %> -->  
        <table style="width: 100%;">
          <tr>
            <td class="" style="margin-right: 1em; width: 15%;"> 
              <% if restaurant.images.count > 0 %>
              <% restaurant.images.each do |image| %>
              <% i = image.name %> <% l = image.location_path%>
              <% path =  l.to_s() + i.to_s() %>
              
              <%= link_to (image_tag path, width: "300", alt: restaurant.name, title: restaurant.name), restaurant %>
            
                <% end %>
            <%end%>
            
            </td>
            <td class="restaurant_name" style="width: 15%;"><%= link_to restaurant.name, restaurant %></td>
            <td class="" style="width: 15%;"><%= restaurant.address %></td>
            <td class="restaurant_description" style="width: ;"><%= restaurant.description %> 
            <div class="actions" style="text-align:right;">
              <span><%= link_to 'View', restaurant %></span>
              <span><%= link_to 'Edit', edit_restaurant_path(restaurant) %></span>
              <!-- <span><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></span> -->
            </div>
            </td>
              
      <!--
      
              <span class=""><%= restaurant.location %></span>
              <span class=""><%= restaurant.gps_lat %></span>
              <span class=""><%= restaurant.gps_lon %></span>
              <span class=""><%= restaurant.category %></span>
      
      <td>
         <div class="actions" style="text-align:right;">
              <span><%= link_to 'Show', restaurant %></span>
              <span><%= link_to 'Edit', edit_restaurant_path(restaurant) %></span>
              <span><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        </div>
        </td>
            -->
    </tr>
    </table>
    <% end %>
  <% end %>
</div>
<br/>

<%= link_to 'New Restaurant', new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div style="width 100%; border: 1px solid black; text-align: left; margin: 1em; padding: 1em;">
<h1>Showing restaurant details</h1>
<p id="notice"><%= notice %></p>

<div id="left_column" style="width: 40%; float: left; border: 0px solid red; margin: 0;">

  <div class="restaurant_name" >
  <%= @restaurant.name %>
  </div>

  <div class="" style="margin-right: 1em; width: 100%;"> 
     <% if @restaurant.images.count > 0 %>
          <% @restaurant.images.each do |image| %>
          <% i = image.name %> <% l = image.location_path%>
          <% path =  l.to_s() + i.to_s() %>
          <%= image_tag path, height: "", width: "100%", alt: @restaurant.name, title: @restaurant.name %>
        <% end %>
    <%end%>    
  </div>

  <div class="restaurant_description"><%= @restaurant.description %></div>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Location:</strong>
  <%= @restaurant.location %>
</p>

<p>
  <strong>Gps lat:</strong>
  <%= @restaurant.gps_lat %>
</p>

<p>
  <strong>Gps lon:</strong>
  <%= @restaurant.gps_lon %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>
  </div>
  
  <div id="center_column" style="width: 30%; border: 0px solid blue; float: left; margin: 0;">
    <div class="restaurant_name">Menu</div>
    <% if @restaurant.dishes.count > 0 %>
    <ul class="dish_name">
      <% @restaurant.dishes.each do |dish| %>
          <li><%= link_to dish.name, dish %></li>
        <% end %>
        </ul>
    <%end%>    
  </div>
  
  <div id="right_column" style="width: 25%; border: 0px solid green; float: right; margin: 0;">
    <div class="restaurant_name">Ratings</div>

    
      <% if @restaurant.restaurant_ratings.count > 0 %>
          <% @restaurant.restaurant_ratings.each do |restaurant_rating| %>
            <%= div_for restaurant_rating, style: "background-color: #FFDBDB;" do %> 
                <p class=""><%= restaurant_rating.content%></p>
                <p class=""><%= restaurant_rating.rate_value%></p>
                <p class="" style="text-align:right;"><%= link_to "Add comment",new_restaurant_rating_restaurant_rating_comment_path(@restaurant) %></p>
                <%end%>
          <%end%>
    <%else%>
      <p>No ratings ...</p>
    <%end%>
    <p class="" style="text-align:right;"><%= link_to "Add rating",new_restaurant_restaurant_rating_path(@restaurant.id) %></p>
    </div>
  <div class="clear_both"></div>
</div>