config/routes.rb
Rails.application.routes.draw do
  root to: 'dishes#show' #show details of a dish on the root

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/restaurant'

  resources :users

  resources :restaurants do
    resources :dishes
    resources :images
    resources :restaurant_ratings do 
      resources :restaurant_rating_comments
    end
  end
resources :restaurant_ratings do 
      resources :restaurant_rating_comments
    end
  
  resources :dishes do
    resources :posts do
      resources :images
      resources :post_comments
    end
    resources :images
    resources :dish_ratings do
      resources :dish_rating_comments
    end
  end

  resources :posts do
    resources :images
    resources :post_comments
  end

  resources :restaurant_ratings do
    resources :restaurant_rating_comments
  end

  resources :post_comments

  resources :dish_rating_comments

  resources :dish_ratings

  resources :images

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dish Rate</title>
    <%= render partial: "shared/includes" %>
  </head>

  <body style="">
    <div id="main_container" style="border: 0px solid green;">
      <header style="border: 0px solid black;">
         <div id="top_header" style="color: #fff; border: 0px solid yellow;" class="clear_both">
            &nbsp;
              <div class="left">
                <!--<%= link_to 'home', root_url %>-->
               <%= link_to (image_tag "logo.png", height: "75", alt: "logo", title: "logo"), root_url %>
              </div>
              <div class="right">
                <ul class="">
                  <li><a href="">Andrzej</a></li>
                  <li><a href="">Sign Up</a></li>
                  <li><a href="">Sign In</a></li>
                  <li><%= link_to 'Help'%></li>
                </ul>
              </div>
          </div>

        <div class="center">
        <div id="top_nav_menu" class="clear_both" style="border: 0px solid black;">
            <ul class="">
              <!--<li><a href="">Restaurants</a></li>-->
              <li><%= link_to 'Restaurants', restaurants_path%></li>
              <li><%= link_to 'Dishes', dishes_path%></li>
              <!-- <li><%= link_to 'Posts', posts_path%></li>-->

              
              <li><%= link_to 'Random Dish', dish_path(Dish.find(Dish.pluck(:id).sample).id) %></li>
              <li><%= link_to 'Random Restaurant', restaurant_path(Restaurant.find(Restaurant.pluck(:id).sample).id) %></li>
              <!-- <li> <%= link_to 'home', root_url %></li> -->
             
              
             
              <li>Serch Restaurants:<input style="margin: 0.25em 1em;" type="text" name="restaurant_search"></li>
              <li>Search Dishes:<input style="margin: 0.25em 1em;" type="text" name="dish_search"></li>
            </ul>
          </div>
          </div>
        &nbsp;
    </header>

      <!--==============================content================================-->
     <div class="content">
       <%= yield %>
     </div>
      
     <!--==============================footer=================================-->
     <footer>
            <div id="footer"> <!-- footer div -->
            <p class="" style="text-align: left;">&copy; Dish Rating App <span>&nbsp;email: <a href="mailto:#####@ncirl.ie">######@ncirl.ie</a></span></p>
             <!--
              <p class="right">
              <a href="http://validator.w3.org">
                <img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Strict" height="23" width="66" /></a>
              </p>
              <p class="right">
              <a href="http://jigsaw.w3.org/css-validator">
                <img width="66px" height="23px"
                  src="http://jigsaw.w3.org/css-validator/images/vcss-blue"
                  alt="Valid CSS!" />
              </a>
            </p>
              -->
          </div> <!-- end of footer div -->
      </footer>
      
    </div><!-- main container end-->
  </body>
</html>